version: 0.2
phases:
  pre_build:
    commands:
      - mvn clean -pl fittable-project/api
  build:
    commands:
      - mvn package -pl fittable-project/api -am -DskipTests=true
artifacts:
  files:
    - fittable-project/api/target/*.jar
  name: fitable-api
  discard-paths: yes
